var config = {
	U_HITO     : '7588806024',
	P_HITO     : '0100599380',
	U_REDMINE  : '8111048370',
	P_REDMINE  : '7640892567',
    O_POSITION : '4067068413',
	LINK_FILTER: '4067068412',
	date : {
		minute:1000 * 60,
		hour:1000 * 60 * 60,
		day: 1000 * 60 * 60 * 24,
		year: 1000 * 60 * 60 * 24 * 365
	},
	genera:{
		is_scan_history:0,
		debug_limit_time:0, // 0 is unlimit , 1,2,3,4 is limit
	},
	hito : {
		urlHitoTime:"https://backend-kintai-hito.lampart-vn.com/api/v1/timestamp/working-time/works-list",
		urlHitoLogin:"https://backend-kintai-hito.lampart-vn.com/api/v1/user/login",
	},
	redmine:{
		REDMINEDOMAIN: "https://project.lampart-vn.com",
        REDMINE_DOMAIN_ISSUES: "https://project.lampart-vn.com/issues/",
        API_MYACC: "/my/account.json",
        API_TIME_ENTRIES: "/time_entries.json",
        API_PROJECT: "/projects.json",
		API_ISSUE:"/issues.json",
		staff: {
			PG :{
				trackers : [6, 7, 18, 5, 10, 11, 1, 9, 23, 24, 25, 27, 32]
			},
			QC :{
				// Review, Task, IT Prepair, IT Tesing
				trackers : [24, 18, 23, 25]
			}
		},
		tracker_activity: new Map([
			["translate",
				{activitys:["translate"]}],
			["spec analytic",
				{activitys:["understand spec", "business analytic"], default:"understand spec"}],
			["coding",
				{activitys:["coding","review code"], 				default:"coding"}],
			["unit testing",
				{activitys:["ut-prepare", "ut-testing"], 			default:"ut-testing"}],
			["review",
				{activitys:["review code", "ut-review"], 			default:"review code"}],
			["bug",
				{activitys:["bug investigation", "ut-review", "review code","coding"], default:"coding"}],
			["feedback",
				{activitys:["coding", "review code"], 				default:"coding"}],
			["it-review",
				{activitys:["it-review"], 			default:"it-review"}],
			["it-prepare",
				{activitys:["it-prepare"], 			default:"it-prepare"}],
			["it-testing",
				{activitys:["it-testing"], 			default:"it-testing"}],
			["task",
				{activitys:["understand spec", "support"], 	default:"understand spec"}],
			["default",
				{activitys:["coding","review code","understand spec","business analysis"], default:"review code"}]
		]),
        activitys: new Map([
        	["translate", 				9],
			["management", 				10],
			["meeting", 				11],
			["explain", 				12],
			["understand spec", 		13],
			["design", 					8],
			["q&a", 					14],
			["coding", 					15],
			["training", 				28],
			["review code", 			16],
			["ut-prepare", 				17],
			["ut-testing", 				18],
			["ut-review", 				19],
			["bug investigation", 		20],
			["merge source", 			21],
			["it-prepare", 				22],
			["it-review", 				23],
			["it-testing", 				24],
			["st-testing", 				25],
			["build dev environment", 	26],
			["prepare release", 		27],
			["working time record & submit", 50],
			["company application process",  51],
			["company information sharing",  52],
			["report & consultation", 		 53],
			["learning", 				54],
			["teaching", 				55],
			["company event", 			56],
			["plan & preparation", 		72],
			["labor union", 			57],
			["break", 					58],
			["evaluation", 				59],
			["problem solving", 		60],
			["recruiting", 				61],
			["working time management", 62],
			["contract", 				63],
			["orientation", 			64],
			["business analysis", 		65],
			["regular operation", 		68],
			["tech research & testing", 69],
			["inquiry handling", 		70],
			["incident handling", 		71],
			["support", 				165],
			["research", 				166]
        ]),
	}
};